name: Release version

on:
  workflow_call:

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    outputs:
      new_release_version: ${{ steps.release.outputs.new_release_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 21.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
