name: Vulnerabilities Scan Workflow

on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        type: string
        description: "Docker image without Dockerhub username"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.docker_image }}
          scan-type: "image"
          format: "json"
          exit-code: 0
          output: "vulnerabilities.json"
          severity: UNKNOWN,CRITICAL,MEDIUM,HIGH,LOW

      - name: Vulnerabilities artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: trivy
          path: vulnerabilities.json
